#!/bin/sh

if [ x$ACTION != xbuild -o -z "$CURRENT_ARCH" -o -z "$INPUT_FILE_NAME" ]; then
    echo "This script is intended to be used as part of an Xcode build process."
    echo "To add Clay files to an Xcode target, open the target settings, go to"
    echo "the \"Rules\" tab, click the \"+\" button to create a custom build"
    echo "rule, and configure it as follows:"
    echo
    echo "    Process:  Source files with names matching:  *.clay"
    echo "    using:    Custom script:"
    echo "      $0"
    echo "    with output files:"
    echo "      \$(DERIVED_FILES_DIR)/\$(INPUT_FILE_BASE).\$(CURRENT_ARCH).s"
    echo
    echo "Then add your main *.clay files (not library clay files!) to the"
    echo "target's \"Compile Sources\" build stage."
    echo "This script will get its input parameters from the Xcode environment."
    exit 1
fi

CLAY=`dirname $0`/clay

INFILE="$INPUT_FILE_NAME"
OUTFILE="$DERIVED_FILES_DIR/$INPUT_FILE_BASE.$CURRENT_ARCH.s"

$CLAY "$@" -o "$OUTFILE" -asm -arch $CURRENT_ARCH "$INFILE"
